export const DEFAULT_BOARD = '00000000000rnbqkbnr00pppppppp00--------00--------00--------00--------00PPPPPPPP00RNBQKBNR0000000000000000000000';
export const EMPTY_BOARD = '00000000000--------00--------00--------00--------00--------00--------00--------00--------0000000000000000000000';

const EMPTY_SQUARE = '-';
const BLACK_ROOK = 'r';
const BLACK_BISHOP = 'b';
const BLACK_KNIGHT = 'n';
const BLACK_QUEEN = 'q';
const BLACK_KING = 'k';
const BLACK_PAWN = 'p';
const WHITE_ROOK = 'R';
const WHITE_BISHOP = 'B';
const WHITE_KNIGHT = 'N';
const WHITE_QUEEN = 'Q';
const WHITE_KING = 'K';
const WHITE_PAWN = 'P';
const WHITE = 'w';
const BLACK = 'b';
const WHITE_QUEENSIDE_ROOK_STARTING_POSITION = 81;
const WHITE_KINGSIDE_ROOK_STARTING_POSITION = 88;
const BLACK_QUEENSIDE_ROOK_STARTING_POSITION = 11;
const BLACK_KINGSIDE_ROOK_STARTING_POSITION = 18;
const BISHOP_MOVE_DIRECTIONS = [9, 11, -9, -11];
const KNIGHT_MOVE_DIRECTIONS = [-12, -21, -19, -8, 12, 21, 19, 8];
const KING_QUEEN_MOVE_DIRECTIONS = [-1, -11, -10, -9, 1, 11, 10, 9];
const ROOK_MOVE_DIRECTIONS = [-1, 1, -10, 10];
const WHITE_PAWN_STARTING_MOVE_DIRECTIONS = [-10, -20];
const BLACK_PAWN_STARTING_MOVE_DIRECTIONS = [10, 20];
const WHITE_PAWN_MOVED_MOVE_DIRECTIONS = [-10];
const BLACK_PAWN_MOVED_MOVE_DIRECTIONS = [10];
const BIT_ON = '1';
const BIT_OFF = '0';
const CURRENT_TURN_BLACK_BIT = 100;
const WHITE_QUEENSIDE_ROOK_MOVED_BIT = 101;
const WHITE_KINGSIDE_ROOK_MOVED_BIT = 102;
const BLACK_QUEENSIDE_ROOK_MOVED_BIT = 103;
const BLACK_KINGSIDE_ROOK_MOVED_BIT = 104;
const WHITE_KING_MOVED_BIT = 105;
const BLACK_KING_MOVED_BIT = 106;
const LAST_MOVE_FROM_TENS = 107;
const LAST_MOVE_FROM_ONES = 108;
const LAST_MOVE_TO_TENS = 109;
const LAST_MOVE_TO_ONES = 110;

export const whitePieces = new Set([
  WHITE_ROOK,
  WHITE_BISHOP,
  WHITE_KNIGHT,
  WHITE_QUEEN,
  WHITE_KING,
  WHITE_PAWN,
]);
export const blackPieces = new Set([
  BLACK_ROOK,
  BLACK_BISHOP,
  BLACK_KNIGHT,
  BLACK_QUEEN,
  BLACK_KING,
  BLACK_PAWN,
]);

export const CONSTANTS = {
  EMPTY_SQUARE,
  BLACK_ROOK,
  BLACK_BISHOP,
  BLACK_KNIGHT,
  BLACK_QUEEN,
  BLACK_KING,
  BLACK_PAWN,
  WHITE_ROOK,
  WHITE_BISHOP,
  WHITE_KNIGHT,
  WHITE_QUEEN,
  WHITE_KING,
  WHITE_PAWN,
  WHITE,
  BLACK,
  WHITE_QUEENSIDE_ROOK_STARTING_POSITION,
  WHITE_KINGSIDE_ROOK_STARTING_POSITION,
  BLACK_QUEENSIDE_ROOK_STARTING_POSITION,
  BLACK_KINGSIDE_ROOK_STARTING_POSITION,
  BISHOP_MOVE_DIRECTIONS,
  KNIGHT_MOVE_DIRECTIONS,
  KING_QUEEN_MOVE_DIRECTIONS,
  ROOK_MOVE_DIRECTIONS,
  WHITE_PAWN_STARTING_MOVE_DIRECTIONS,
  BLACK_PAWN_STARTING_MOVE_DIRECTIONS,
  WHITE_PAWN_MOVED_MOVE_DIRECTIONS,
  BLACK_PAWN_MOVED_MOVE_DIRECTIONS,
  BIT_ON,
  BIT_OFF,
  CURRENT_TURN_BLACK_BIT,
  WHITE_QUEENSIDE_ROOK_MOVED_BIT,
  WHITE_KINGSIDE_ROOK_MOVED_BIT,
  BLACK_QUEENSIDE_ROOK_MOVED_BIT,
  BLACK_KINGSIDE_ROOK_MOVED_BIT,
  WHITE_KING_MOVED_BIT,
  BLACK_KING_MOVED_BIT,
  LAST_MOVE_FROM_TENS,
  LAST_MOVE_FROM_ONES,
  LAST_MOVE_TO_TENS,
  LAST_MOVE_TO_ONES,
};
